### ISSUE TITLE
What Openstack version Kubestack support ?

### ISSUE THREAD

**Issue by rkamudhan** [hyperhq/kubestack#17] opened 2016-07-22 17:01 UTC
@feiskyer Current Openstack version mitaka having an issue in getting the initialURL, is there specific openstack version we have to use for the kubestack and gophercloud ? I am having a problem in getting url and dns_name...

**Comment by feiskyer** [comment] 2016-07-25 06:17
@rkamudhan Thanks for reporting the problem. Kubestack is developed with liberty and it should support mitaka in theory.

Could you explain the problem in detail?

**Comment by rkamudhan** [comment] 2016-07-25 07:59
It is supporting, but I had to make code changes in the openstack.go file and should enable dns integration for the openstack. Is that dns_integration must be enabled for the openstack ? Also, the kubestack is not pulling the current version of gophercloud. There are few things should be taken care before integrating the openstack and gophercloud. With the current installation, the Mitaka won't  work, because it refers to an invalid initial URL without adding "v2" in it, and openstack throw 404 error.

`kubestack.go:82] CheckTenantID result {false Expected HTTP response code [200 204] when accessing [GET http://<keystone IP address>/identity_v2_admin/tenants], but got 404 instead
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}}
`

And without dns_integration, we get
`openstack.go:655] Create port kube_ubuntu_ns1_<neutron_network_id> failed: Expected HTTP response code [201 202] when accessing [POST http://<keystone IP address>:9696/v2.0/ports], but got 400 instead
{"NeutronError": {"message": "Unrecognized attribute(s) 'dns_name'", "type": "HTTPBadRequest", "detail": ""}}`

I able to fix the issue, but I need to know whether it is bug or it should be taken care by the developer.

**Comment by feiskyer** [comment] 2016-07-25 08:25
@rkamudhan Thanks. dns_integration is required because kube-dns doesn't work with neutron's multi-tenant network.

I will file another PR to solve identity problem.

**Comment by feiskyer** [comment] 2016-07-27 04:08
@rkamudhan Could you verify whether PR #18 solves your problem?

**Comment by rkamudhan** [comment] 2016-08-01 20:00
PR #18  throws the following error , whenever I run the /usr/local/bin/kubestack

`Couldn't initialize openstack: gophercloud.ErrDefault401{ErrUnexpectedResponseCode:gophercloud.ErrUnexpectedResponseCode{BaseError:gophercloud.BaseError{DefaultErrString:"", Info:""}, URL:"http://<keystone>:5000/v2.0/tokens", Method:"POST", Expected:[]int{200, 203}, Actual:401, Body:[]uint8{0x7b, 0x22, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3a, 0x20, 0x7b, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x54, 0x68, 0x65, 0x20, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x20, 0x79, 0x6f, 0x75, 0x20, 0x68, 0x61, 0x76, 0x65, 0x20, 0x6d, 0x61, 0x64, 0x65, 0x20, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x20, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x22, 0x2c, 0x20, 0x22, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3a, 0x20, 0x34, 0x30, 0x31, 0x2c, 0x20, 0x22, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x7d, 0x7d}}}`

Kubestack refering to the invalid url http://keystone:5000/v2.0/tokens, Could you please tell me, in which openstack version you testing the kubestack ?

**Comment by feiskyer** [comment] 2016-08-02 03:22
@rkamudhan The PR is tested on both version L and M, and `gophercloud` has been updated to latest version. 

Maybe there are some configurations differently in your environments? My test environment is deployed by [RDO](https://www.rdoproject.org/) with default configurations.

**Comment by rkamudhan** [comment] 2016-08-02 08:21
@feiskyer Thanks for the fixes, I will check into my environment issues. I am also testing in the RDO, let me check it again and get back to you. Thanks again for your fast response.

**Comment by feiskyer** [comment] 2016-08-02 08:27
@rkamudhan Maybe you are using keystone v3 by default? I'm using keystone v2, and all neutron commands are requesting tokens from `http://keystone:5000/v2.0/tokens`:

``` sh
# neutron --debug net-list
...
DEBUG: keystoneauth.identity.v2 Making authentication request to http://172.31.30.250:5000/v2.0/tokens
...
```

**Comment by rkamudhan** [comment] 2016-08-02 09:07
I am getting the following URL value for my devstack installation, 

`$ neutron --debug net-list
.....
DEBUG: keystoneauth.identity.v2 Making authentication request to http://10.237.216.224/identity/v2.0/tokens
`

Kubestack without #18  is working fine for me, with few changes in openstack.go, I added  `openstack.NewIdentityV2(provider)` function inside the `NewOpenStack()` to resolve the 

`kubestack.go:82] CheckTenantID result {false Expected HTTP response code [200 204] when accessing [GET http://<keystone IP address>/identity_v2_admin/tenants], but got 404 instead {"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}}`

and installed dns_integration in devstack and overall installation is working fine, but working with #18 failed with kubestack.service

**Comment by feiskyer** [comment] 2016-08-02 09:12
@rkamudhan  Weird, there should be some errors in keystone endpoints. `http://<keystone IP address>/identity_v2_admin/tenants` is gotten from keystone, but reported 404 in your environment.

**Comment by rkamudhan** [comment] 2016-08-02 10:08
Could you please share your's `openstack endpoint show <Keystone endpoint ID>` values ? It will help me to narrow down the issue.

**Comment by feiskyer** [comment] 2016-08-02 10:50
``` sh
# openstack endpoint show keystone
+--------------+----------------------------------+
| Field        | Value                            |
+--------------+----------------------------------+
| adminurl     | http://ip-address:35357/v2.0  |
| enabled      | True                             |
| id           | 7c647ba778e441baa69325673f626de1 |
| internalurl  | http://ip-address:5000/v2.0   |
| publicurl    | http://ip-address:5000/v2.0   |
| region       | RegionOne                        |
| service_id   | 69044b08c70f4f788ab3163ad2dedfbd |
| service_name | keystone                         |
| service_type | identity                         |
+--------------+----------------------------------+
```

**Comment by rkamudhan** [comment] 2016-08-02 14:21
| Field | Value |
| --- | --- |
| adminurl | http://ip-address/identity_v2_admin |
| enabled | True |
| id | 13ae4eebae85453fb299721fc2b5c6ad |
| internalurl | http://ip-address/identity |
| publicurl | http://ip-address/identity |
| region | RegionOne |
| service_id | 7c9def0626fd4925bf77b432f00fc1f7 |
| service_name | keystone |
| service_type | identity |

This is my results, I am using devstack installation, So it means that kubestack won't support devstack ?

**Comment by rkamudhan** [comment] 2016-08-03 08:28
I figured out the issue in my environment, the problem was due to bad configuration.

**Comment by feiskyer** [comment] 2016-08-05 02:20
@rkamudhan I'm closing this issue since you have already find the root cause. You can reopen it if you think it is needed.

**Closed as completed by feiskyer** 2016-08-05 02:20 UTC
